charlist/urls.py
from django.contrib import admin
from django.urls import path, include
from charlist.settings import DEBUG

import personages.views as personages
import myauth.views as myauth

urlpatterns = [
    path('personage/', include('personages.urls', namespace='personages')),
    path('myauth/', include('myauth.urls', namespace='myauth')),
    path('all_personages/', personages.all_personages, name='all_personages'),

    path('admin/', admin.site.urls),
    # path('__debug__/', include('debug_toolbar.urls')),
]
#
# if DEBUG:
#     urlpatterns += path('__debug__/', include('debug_toolbar.urls'))

myauth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
import myauth.views as myauth

app_name = 'myauth'

urlpatterns = [

    path('register/', myauth.NewUserRegister.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

personages/urls.py
from django.urls import path, include  # pylint: disable=unused-import

import personages.views as personages

app_name = 'personages'

urlpatterns = [

    path('details/<int:pk>/', personages.PersonageDetailView.as_view(), name='details'),
    path('create/', personages.PersonageCreateView.as_view(template_name="personages/personage_create.html"), name='create'),
    path('create2/', personages.PersonageCreateView.as_view(template_name="personages/personage_form.html"), name='create2'),
    path('details2/<int:pk>/', personages.personage_details2, name='details2'),
    path('update/<int:pk>/', personages.PersonageUpdateView.as_view(template_name="personages/personage_update.html"), name='update'),


]

myauth/models.py
from django.contrib.auth.models import User, AbstractUser
from django.db import models


# расширение дефолтного User
# class NewUserProfile(models.Model):
#     user = models.OneToOneField(User,
#                                 on_delete=models.CASCADE,
#                                 primary_key=True)
#     avatar = models.ImageField(upload_to='avatars', blank=True)

class CharlistUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars', blank=True)

personages/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from myauth.models import CharlistUser


class Personage(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(CharlistUser, on_delete=models.SET_NULL, null=True)
    # group_id = models.ForeignKey(на группу пользователей)
    pers_name = models.CharField(max_length=64)
    pers_pronoun = models.CharField(max_length=64)
    pers_description = models.TextField(blank=True)
    refresh = models.IntegerField(null=True)
    fate_points = models.IntegerField(null=True)
    aspect1 = models.CharField(max_length=256, blank=True)
    aspect2 = models.CharField(max_length=256, blank=True)
    aspect3 = models.CharField(max_length=256, blank=True)
    aspect4 = models.CharField(max_length=256, blank=True)
    aspect5 = models.CharField(max_length=256, blank=True)
    aspect6 = models.CharField(max_length=256, blank=True)
    approach1_name = models.CharField(max_length=256, blank=True)
    approach1_value = models.IntegerField(null=True)
    approach2_name = models.CharField(max_length=256, blank=True)
    approach2_value = models.IntegerField(null=True)
    approach3_name = models.CharField(max_length=256, blank=True)
    approach3_value = models.IntegerField(null=True)
    approach4_name = models.CharField(max_length=256, blank=True)
    approach4_value = models.IntegerField(null=True)
    approach5_name = models.CharField(max_length=256, blank=True)
    approach5_value = models.IntegerField(null=True)
    approach6_name = models.CharField(max_length=256, blank=True)
    approach6_value = models.IntegerField(null=True)
    stunts = models.TextField(blank=True)
    extras = models.TextField(blank=True)
    stress = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(3)], default=0)
    consequences_mild = models.CharField(max_length=256, blank=True)
    consequences_moderate = models.CharField(max_length=256, blank=True)
    consequences_severe = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return f"Personage: \n" \
               f"name: {self.pers_name}, pronoun: {self.pers_pronoun!r}, " \
               f"description: {self.pers_description!r}"

    def get_parties(self):
        party = self.personageparty_set.all()
        return ', '.join(map(str, party))

    def get_aspects(self):
        return self.aspect1, self.aspect2, self.aspect3, self.aspect4, self.aspect5, self.aspect6


class PersonageParty(models.Model):
    party = models.CharField(max_length=64)
    personage = models.ManyToManyField(Personage)

    def __str__(self):
        return self.party

myauth/forms.py
from django.contrib.auth.forms import UserCreationForm

from myauth.models import CharlistUser


class CharlistUserCreateForm(UserCreationForm):
    class Meta:
        model = CharlistUser
        fields = ('username', 'email', 'password1', 'password2')

personages/forms.py
from django.forms import ModelForm

from personages.models import Personage


class PersonageCreateForm(ModelForm):
    class Meta:
        model = Personage
        fields = '__all__'
        exclude = ('id', 'user_id')

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            print(name)
            field.widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        self.instance.user_id = self._user
        return super().save(commit)

myauth/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from myauth.forms import CharlistUserCreateForm
from myauth.models import CharlistUser


class NewUserRegister(CreateView):
    model = CharlistUser
    success_url = reverse_lazy('all_personages')
    # success_url = '/' # должен быть реверс лейзи по хорошему
    form_class = CharlistUserCreateForm

personages/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView
from personages.models import Personage

from personages.forms import PersonageCreateForm


@login_required
def all_personages(request):
    all_personages = Personage.objects.filter(
        user_id=request.user)

    context = {
        'all_personages': all_personages,
    }

    return render(request, 'personages/all_personages.html', context=context)


# вариант CBV - Class Detail View
class PersonageDetailView(DetailView):
    template_name = 'personages/personage_detail.html'  # автоматически вычисляется из имя класса + _detail
    model = Personage
    page_title = 'Personage detail'

    # pk_url_kwarg = 'pk' # нужно, если как primary key используется не 'pk' или 'slug'
    # context_object_name = 'personage_details' # можно переопределять, если нужен кастом,
    # но если не определено, за контекст берется имя класса
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(
            user_id=self.request.user
        )


class PersonageCreateView(LoginRequiredMixin, CreateView):
    model = Personage
    success_url = reverse_lazy('all_personages')
    form_class = PersonageCreateForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class PersonageUpdateView(LoginRequiredMixin, UpdateView):
    model = Personage
    success_url = reverse_lazy('all_personages')
    form_class = PersonageCreateForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


# вариант FBV - Function Detailed View
def personage_details2(request, pk):
    get_personage_details = get_object_or_404(Personage, pk=pk)

    context = {
        'page_title': 'Detail title',
        'personage': get_personage_details,  # контекст следует называть четко по имени класса
    }

    return render(request, 'personages/personage_detail.html', context=context)


# вариант FBV - Function Detailed View
def personage_create2(request):
    personage = Personage()
    personage.save()
    context = {
        'page_title': 'Detail title',
        'personage': personage,  # контекст следует называть четко по имени класса
    }

    return render(request, 'personages/personage_create.html', context=context)

myauth/templates/myauth/charlistuser_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User</title>
</head>
<body>
<div class="user-creation-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">
    </form>
</div>
</body>
</html>

personages/templates/personages/all_personages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Personages</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/main.css">
</head>

{% extends 'personages/base.html' %}
<body>
{% block main_content %}

<h1>View all personages</h1>

<ol class="list-group list-group-numbered"> {% for el in all_personages %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
            <a href="{% url 'personages:details' pk=el.pk %}">
                <div class="fw-bold">{{ el.pers_name }}</div>
            </a>
            <small>{{ el.pers_description }}</small>

        </div>
        {% if el.get_parties %}
        <span class="badge bg-primary rounded-pill"> {{ el.get_parties }} </span>
        {% endif %}
    </li>

    {% endfor %}
</ol>
{% endblock %}
</body>
</html>

personages/templates/personages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"Charlist" }}</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

</head>
<body>

{% block menu %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Hello {{user}}!</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_anonimous %}
                    <a class="nav-link" href="{% url 'myauth:login' %}"> Login </a>
                    {% else %}
                    <a class="nav-link" href="{% url 'myauth:logout' %}"> Logout </a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'all_personages' %}">All personages</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'personages:create'%}">Create new personage</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% endblock %}

{% block main_content %}
{% endblock %}

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>
</html>

personages/templates/personages/personage_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Personage action</title>

</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <!--    {{ form.as_table }} дорабатывать таблицу дополнительно-->
    <!--    {{ form.as_ul }} дорабатывать список дополнительно -->

    <input type="submit" value="save">
</form>
</body>
</html>